### ISSUE TITLE
Allow versions > 1.4

### ISSUE THREAD

**Issue by jersub** [saltstack-formulas/logstash-formula#8]
At the time of writing, versions 1.5 and 2.0 are out. Users should be able to choose their Logstash version.

**Comment by johnkeates** [comment]
This is implemented via #16

**Comment by absmith82** [comment]
addressed with pr#29

**Comment by absmith82** [comment]
This is fixed as of PR #29 which was recently merged.

**Comment by OrangeDog** [comment]
Why is this issue not closed?

**Comment by absmith82** [comment]
I agree this should be closed.
